[package]
name = "ckb-merkle-tree"
version = "0.19.2"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]
merkle-cbt = "0.2"
ckb-hash = { path = "../hash"}
numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
